[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "tfod2-vscode-demo"
version = "1.0.0"
description = "VS Code friendly TensorFlow Object Detection 2 inference tasks."
requires-python = ">=3.9,<3.12"

[tool.setuptools.packages.find]
where = ["src"]

